// <auto-generated />
using System;
using ExposureTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExposureTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220704021327_uwLifeDataUAT")]
    partial class uwLifeDataUAT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExposureTracker.Models.Insured", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("baserider")
                        .HasColumnType("text");

                    b.Property<string>("benefittype")
                        .HasColumnType("text");

                    b.Property<string>("bordereauxfilename")
                        .HasColumnType("text");

                    b.Property<int?>("bordereauxyear")
                        .HasColumnType("integer");

                    b.Property<string>("cedantcode")
                        .HasColumnType("text");

                    b.Property<string>("cedingcompany")
                        .HasColumnType("text");

                    b.Property<string>("certificate")
                        .HasColumnType("text");

                    b.Property<string>("clientid")
                        .HasColumnType("text");

                    b.Property<string>("currency")
                        .HasColumnType("text");

                    b.Property<string>("dateofbirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dateuploaded")
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .HasColumnType("text");

                    b.Property<string>("middlename")
                        .HasColumnType("text");

                    b.Property<string>("mortalityrating")
                        .HasColumnType("text");

                    b.Property<string>("plan")
                        .HasColumnType("text");

                    b.Property<string>("planeffectivedate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("policyno")
                        .HasColumnType("text");

                    b.Property<decimal>("reinsurednetamountatrisk")
                        .HasColumnType("numeric");

                    b.Property<string>("soaperiod")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<decimal>("sumassured")
                        .HasColumnType("numeric");

                    b.Property<string>("typeofbusiness")
                        .HasColumnType("text");

                    b.Property<string>("uploadedby")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("dbLifeData");
                });

            modelBuilder.Entity("ExposureTracker.Models.TranslationTables", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("base_rider")
                        .HasColumnType("text");

                    b.Property<string>("benefit_cover")
                        .HasColumnType("text");

                    b.Property<string>("cedant_code")
                        .HasColumnType("text");

                    b.Property<string>("ceding_company")
                        .HasColumnType("text");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insured_prod")
                        .HasColumnType("text");

                    b.Property<string>("plan_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prod_description")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("dbTranslationTable");
                });
#pragma warning restore 612, 618
        }
    }
}
